# Generated by Django 4.0.3 on 2022-04-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_test2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test2',
            table='test2',
        ),
    ]
